version: '3.8'

services:
  document-processor:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: advanced-document-processor
    volumes:
      # Mount local directories for persistent data with proper permissions
      - ./docs:/app/docs:rw
      - ./outputs:/app/outputs:rw
      - ./cache:/app/cache:rw
      - ./config.json:/app/config.json:ro
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    working_dir: /app
    stdin_open: true
    tty: true
    # Expose port for future web interface
    ports:
      - "8000:8000"
    # Optimized resource limits for production
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    # Enhanced health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.append('/app'); from src.embedder import PersonaEmbedder; print('Healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Security and reliability settings
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a lightweight web interface container (future enhancement)
  # web-interface:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.web
  #   container_name: document-processor-web
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - document-processor
  #   restart: unless-stopped

volumes:
  model_cache:
    driver: local
  processing_cache:
    driver: local

networks:
  default:
    name: document-processor-network
    driver: bridge
